---
abstract: 'Tracks Good/Bad for people'
author: ~
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bot-BasicBot-Pluggable-Module-GoodBad
no_index:
  directory:
    - inc
    - t
requires:
  Bot::BasicBot::Pluggable: 0
version: 0.02
